### PR TITLE
Forcing the input eigen matrix to be csc when copying it into an osqp matrix

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Thanks @S-Dafarra for working on this. This should fix the problem spotted in  https://github.com/robotology/osqp-eigen/pull/54, right?

**Comment by S-Dafarra** [comment]
>Thanks @S-Dafarra for working on this. This should fix the problem spotted in #54, right?

That was the idea, even if I did not add a proper test for it. Any idea?

**Comment by S-Dafarra** [comment]
> That was the idea, even if I did not add a proper test for it. Any idea?

In https://github.com/robotology/osqp-eigen/pull/57/commits/ad6d2a316a235199751b03c230273d881829606d I added a simple test that is failing with the ``devel`` version but not with the patch.

**Comment by GiulioRomualdi** [comment]
> > That was the idea, even if I did not add a proper test for it. Any idea?
> 
> In [ad6d2a3](https://github.com/robotology/osqp-eigen/commit/ad6d2a316a235199751b03c230273d881829606d) I added a simple test that is failing with the `devel` version but not with the patch.

Perfect. You can bump the version from `0.6.101` to `0.6.102` and then merge!

**Comment by S-Dafarra** [comment]
I just bumped to ``0.6.102`` in #52 :grin: If you agree, we can land #52 first and then I bump the version of this one :grin:

**Comment by GiulioRomualdi** [comment]
Deal!

**Comment by S-Dafarra** [comment]
Bumped to ``0.6.103``. Ready to merge.

**Pull request merged**
