### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cybaol**

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks a lot for the fixes @cybaol! 

fyi @S-Dafarra @GiulioRomualdi

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Thank you very much!

**Comment by traversaro** [comment]
CI failures actually due to https://github.com/robotology/osqp-eigen/issues/161 .

**Comment by GiulioRomualdi** [comment]
Ci failure is not related to this PR. Merging

**Pull request merged**
