### PR TITLE
General CI cleanup November 2024

### PR DESCRIPTION
**Pull request by traversaro**
* Migrate from catch2 2.* to 3.* (similar to https://github.com/ami-iit/matio-cpp/pull/56)
* Drop homebrew CI (fix https://github.com/robotology/osqp-eigen/issues/161)
* Add job on macOS, Windows and Linux that runs tests with conda-forge dependencies using pixi.
 
The main advantage of pixi that to replicate the tests on your machine you just need to run:

~~~
git clone https://github.com/robotology/osqp-eigen/
cd osqp-eigen
pixi run test
~~~

### CODE REVIEW

**Comment by traversaro** [comment]
Valgrind test:

~~~
10/10 Test #10: memcheck_MPCUpdateMatricesUnitTests ...***Failed    0.01 sec
==3479== Memcheck, a memory error detector
==3479== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==3479== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==3479== Command: /home/runner/work/osqp-eigen/osqp-eigen/.build/MPCUpdateMatricesUnitTests
==3479== 

valgrind:  Fatal error at startup: a function redirection
valgrind:  which is mandatory for this platform-tool combination
valgrind:  cannot be set up.  Details of the redirection are:
valgrind:  
valgrind:  A must-be-redirected function
valgrind:  whose name matches the pattern:      strcmp
valgrind:  in an object with soname matching:   ld-linux-x86-64.so.2
valgrind:  was not found whilst processing
valgrind:  symbols from the object with soname: ld-linux-x86-64.so.2
valgrind:  
valgrind:  Possible fixes: (1, short term): install glibc's debuginfo
valgrind:  package on this machine.  (2, longer term): ask the packagers
valgrind:  for your Linux distribution to please in future ship a non-
valgrind:  stripped ld.so (or whatever the dynamic linker .so is called)
valgrind:  that exports the above-named function using the standard
valgrind:  calling conventions for this platform.  The package you need
valgrind:  to install for fix (1) is called
valgrind:  
valgrind:    On Debian, Ubuntu:                 libc6-dbg
valgrind:    On SuSE, openSuSE, Fedora, RHEL:   glibc-debuginfo
valgrind:  
valgrind:  Note that if you are debugging a 32 bit process on a
valgrind:  64 bit system, you will need a corresponding 32 bit debuginfo
valgrind:  package (e.g. libc6-dbg:i386).
valgrind:  
valgrind:  Cannot continue -- exiting now.  Sorry.
~~~

So I guess we need to install `libc6-dbg` even if we use pixi if we want to use valgrind.

**Comment by traversaro** [comment]
> So I guess we need to install `libc6-dbg` even if we use pixi if we want to use valgrind.

I did this, and now the PR is ready for review.

**Comment by pauldreik** [comment]
Yay for fixing the tests and upgrading catch! Is there anything technical holding this back @GiulioRomualdi ?

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Hi @pauldreik . No technical issues on my side. I'll go ahead and merge it. Thanks!

**Pull request merged**
