### PR TITLE
Add FindEigen3.cmake

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This allows using osqp-eigen on a Windows machine.

See  #18 

cc @S-Dafarra @traversaro

### CODE REVIEW

**Comment by traversaro** [comment]
Note that this is necessary because the Eigen3 provided by the YARP installers do not contain a `Eigen3Config.cmake` , see https://github.com/robotology/icub-packaging/issues/8 . 

Until we fix that issue, indeed the only option is to vendor `FindEigen3.cmake` in every project (or add a dependency on a project that provides it, but I agree that this is not desirable for a project like `osqp-eigen`). However, I suggest to vendor a more recent version of `FindEigen3.cmake` (for example the one provided in https://bitbucket.org/eigen/eigen/src/default/cmake/FindEigen3.cmake) to make sure that the FindEigen3.cmake defines the `Eigen3::Eigen` imported target, for compatibility with the official CMake config file. 

Note that the issue is complicated by the fact that in this library Eigen3 is used in the public interface of the library (obviously, given the nature of the library), so in the `OsqpEigenConfig.cmake` on a empty project could fail because the empty project does not have a `FindEigen3.cmake` . This is typically not a big problem because every Eigen-using project provide its own `FindEigen3.cmake`, but it is something you may want to be aware of.

**Comment by GiulioRomualdi** [comment]
In f5695db the latest version of [`FindEigen3.cmake`](https://bitbucket.org/eigen/eigen/src/default/cmake/FindEigen3.cmake?fileviewer=file-view-default) is used.

**Comment by traversaro** [comment]
Great, let's merge.

**Comment by traversaro** [comment]
@S-Dafarra @GiulioRomualdi consider anyhow that https://github.com/robotology/icub-packaging/issues/8 may affect you in the future, also in `levi` or similar libraries.

**Comment by S-Dafarra** [comment]
Indeed I had to add a ``FindEigen3.cmake`` also in ``levi``. So when https://github.com/robotology/icub-packaging/issues/8 is closed we can get rid of that file?

**Comment by traversaro** [comment]
Yes, at least if we assume that Eigen3 is installed in the system using our installer or anyone in a way that such that a `Eigen3Config.cmake` file is available.

**Pull request merged**
