### PR TITLE
Use Eigen:Ref and Eigen::SparseCompressedBased object (Copy of #23)

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This is a copy of #23. Indeed since I did `push -force` in the master branch (I am sure there exists a [circle of hell](https://en.wikipedia.org/wiki/Inferno_(Dante)#Nine_circles_of_Hell) for this) #23 is corrupted. 

As suggested by @traversaro in https://github.com/robotology/osqp-eigen/pull/23#issuecomment-481174583 I created a [tag](https://github.com/robotology/osqp-eigen/releases/tag/v0.3.0) that points to the last commit before this PR.

**Notice**: the base of PR is `release-0.4.0` and not master. Probably this will cause problems in the [superbuild](https://github.com/robotology/robotology-superbuild), however, I prefer extensively testing the new API before merging in master. 

What do you think @S-Dafarra and @traversaro?

### CODE REVIEW

**Comment by traversaro** [comment]
> Notice: the base of PR is release-0.4.0 and not master. Probably this will cause problems in the superbuild, however, I prefer extensively testing the new API before merging in master.

As long as the commits for `osqp-eigen` and any software that uses `osqp-eigen` are coherent in the master branch of the superbuild, there are no problems.

**Comment by GiulioRomualdi** [comment]
> > Notice: the base of PR is release-0.4.0 and not master. Probably this will cause problems in the superbuild, however, I prefer extensively testing the new API before merging in master.
> 
> As long as the commits for `osqp-eigen` and any software that uses `osqp-eigen` are coherent in the master branch of the superbuild, there are no problems.

Yes, you are right but in the next future the new version of the walking controller will be based on the version `0.4.0`

**Comment by traversaro** [comment]
> Yes, you are right but in the next future the new version of the walking controller will be based on the version 0.4.0

Probably this is a bit OT here, anyhow: the new version of walking controller refers to `master` or `devel` branch of `walking-controllers`  ? 

Anyhow, if you need any different branch for `walking-controllers`/`osqp-eigen` in the superbuild, just specify them in the https://github.com/robotology/robotology-superbuild/blob/master/cmake/ProjectsTagsMaster.cmake and https://github.com/robotology/robotology-superbuild/blob/master/cmake/ProjectsTagsDevel.cmake . See for example https://github.com/robotology/robotology-superbuild/pull/172 and https://github.com/robotology/robotology-superbuild/pull/194 .

**Comment by traversaro** [comment]
Let me know if @S-Dafarra is not able to review the PR, as I would need some time to actually check the details of the PR.

**Comment by traversaro** [comment]
Anyhow, if you plan to keep the `release-0.4.0` branch around for some time, why not goint for a classical `devel` branch?

**Comment by S-Dafarra** [comment]
Given that this is a copy of https://github.com/robotology/osqp-eigen/pull/23 I don't have other specific comments.
Just to know, for other releases you will also plan to create a separate branch and merge there?

**Comment by GiulioRomualdi** [comment]
> Anyhow, if you plan to keep the `release-0.4.0` branch around for some time, why not goint for a classical `devel` branch?

Yes, probably instead of having `release-0.4.0` branch we can use `devel`

**Pull request merged**
