### PR TITLE
Use Eigen:Ref and Eigen::SparseCompressedBased object

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
With this PR:
* the methods `setUpperBound` `setLowerBound` `setGradient` `updateUpperBound` `updateLowerBound` `updateGradient` are no more template functions.
* the methods related to the sparse matrices take as imput an `Eigen::SparseCompressedBased` object instead of `Eigen::SparseMatrix`.

As side effect now it is possible to pass and `Eigen::Map` to the function instead of an `Eigen::MatrixXd`

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Related to #17

**Comment by traversaro** [comment]
Given that this changes the API, I think it would be nice to: 
* Bump the minor version in CMake, so that downstream user can check the version and raise a CMake error (or change the code they are compiling) depending on the version
* Document in the README the policy regarding API changes

**Comment by traversaro** [comment]
It would be nice also to release 0.3.0 or 0.3.1 that points to the last commit before this PR, so if there are downstream users targeting the old API, they can just point to the relevant tag.

**Comment by GiulioRomualdi** [comment]
@traversaro 
> It would be nice also to release 0.3.0 or 0.3.1 that points to the last commit before this PR, so if there are downstream users targeting the old API, they can just point to the relevant tag.

Regarding the versioning, we should define the mode in which the version is changed. If I do not make a mistake in general when the `x.y.z` versioning system is used the `z` number is changed only when some bugs are fixed. On the other hand, when the API changes `y` should be increased.

@traversaro, are there some guidelines for software versioning in robotology?

**Comment by S-Dafarra** [comment]
I guess here https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md#example there is a good guideline on how to define the version.

**Comment by GiulioRomualdi** [comment]
> I guess here https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md#example there is a good guideline on how to define the version.

Ok so It should be 0.4.0 (since we are introducing new API)

**Comment by traversaro** [comment]
Exactly, YARP versioning scheme is a good model, https://semver.org/ is another commonly used reference.

**Pull request closed without merging**
