### PR TITLE
[Solver.tpp] add warning message to updateHessianMatrix and updateLinearConstraintsMatrix for RowMajor

### PR DESCRIPTION
**Pull request by Naoki-Hiraoka**
Hello. I am a user of  OsqpEigen.

`OsqpEigen::Solver::updateHessianMatrix` and `OsqpEigen::Solver::updateLinearConstraintsMatrix` do not support RowMajor matrix
because `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets` does not support RowMajor matrix.

I have added warning message to inform users of this.

### CODE REVIEW

**Comment by Naoki-Hiraoka** [comment]
Supplementary explanation.

The order of the Triplets returned by `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets ` is different depending on whether input matrix is RowMajor or ColMajor.  `OsqpEigen::Solver::evaluateNewValues` ​​can not compare correctly in RowMajor case.

**Comment by S-Dafarra** [comment]
Hi @Naoki-Hiraoka,

thanks for the PR, and apologies for the late answer. 

> `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets` does not support RowMajor matrix.

To be honest, this is not really clear to me. 
The function `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets ` iterates over the non-zero elements with the following ``for`` loop
https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/SparseMatrixHelper.tpp#L139-L144

Depending on if the matrix is ``RowMajor`` or ``ColMajor`` the outer size and the inner size change, but both should be supported.

In particular, 

> The order of the Triplets returned by `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets ` is different depending on whether input matrix is RowMajor or ColMajor. `OsqpEigen::Solver::evaluateNewValues` ​​can not compare correctly in RowMajor case.

is indeed expected. This problem arises when the solver is initialized with a ``ColMajor`` matrix and then updated with a ``RowMajor`` matrix. In this case, ``evaluateNewValues`` should return ``false`` and reinitialize the problem.

So, in the end ``RowMajor`` **is** supported.

**Comment by Naoki-Hiraoka** [comment]
Thank you for response!

I'm sorry for my inaccurate description, but I think `RowMajor` is **not** supported.

As you say, `OsqpEigen::SparseMatrixHelper::eigenSparseMatrixToTriplets` and `OsqpEigen::Solver::evaluateNewValues` support RowMajor matrix. (My previous comments were incorrect.)

> This problem arises when the solver is initialized with a ColMajor matrix and then updated with a RowMajor matrix. In this case, evaluateNewValues should return false and reinitialize the problem.

However, the solver is always initialized with a `ColMajor` matrix
because `OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix` converts the input matrix to `ColMajor`.
 And `OsqpEigen::SparseMatrixHelper::osqpSparseMatrixToTriplets` does not support `RowMajor matrix`.

https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/SparseMatrixHelper.tpp#L13

https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/SparseMatrixHelper.tpp#L84

**Comment by S-Dafarra** [comment]
> However, the solver is always initialized with a `ColMajor` matrix
> because `OsqpEigen::SparseMatrixHelper::createOsqpSparseMatrix` converts the input matrix to `ColMajor`.

Ah I see, good catch! Indeed, the core problem is that an ``osqp`` sparse matrix is always ``ColMajor``. That's why we convert a ``RowMajor`` matrix when initializing the solver. But then when updating ``evaluateNewValues`` would always return ``false``. 

I guess that the problem then is to improve [evaluateNewValues](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L310) such that the check is not [dependent on the triplets' order](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L321-L323), or to modify [``selectUpperTriangularTriplets``](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L346) such that the output is the same independently of ``ColMajor`` or ``RowMajor``.

**Comment by traversaro** [comment]
> I guess that the problem then is to improve [evaluateNewValues](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L310) such that the check is not [dependent on the triplets' order](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L321-L323), or to modify [`eigenSparseMatrixToTriplets`](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/SparseMatrixHelper.tpp#L127) such that the output is the same independently of `ColMajor` or `RowMajor`.

Hello @S-Dafarra and @Naoki-Hiraoka, some time has passed, do you know if this problem is still present? If it is, probably it could make sense to move this PR to an issue? Thanks!

**Comment by S-Dafarra** [comment]
> > I guess that the problem then is to improve [evaluateNewValues](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L310) such that the check is not [dependent on the triplets' order](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/Solver.tpp#L321-L323), or to modify [`eigenSparseMatrixToTriplets`](https://github.com/robotology/osqp-eigen/blob/bba25ca59be224546abbd6470944e19a41ab455c/include/OsqpEigen/SparseMatrixHelper.tpp#L127) such that the output is the same independently of `ColMajor` or `RowMajor`.
> 
> Hello @S-Dafarra and @Naoki-Hiraoka, some time has passed, do you know if this problem is still present? If it is, probably it could make sense to move this PR to an issue? Thanks!

Hi @traversaro, I think that the problem is still there. Corresponding issue: https://github.com/robotology/osqp-eigen/issues/168

**Comment by traversaro** [comment]
Great, thanks! I think at this point we can close this PR, and open a new one if someone wants to solve https://github.com/robotology/osqp-eigen/issues/168 .

**Pull request closed without merging**
