### PR TITLE
Add the possibility to solve unconstrained QP problem without setting the constraint matrix

### LINKED ISSUE #84: Solve unconstrained optimization problems
This issue shows how to set `osqp-eigen` to solve an unconstrained optimization problem

We now want to solve the following optimization problem

<center>qp</center>

The solution of the problem is `x = [0 0]` 

`osqp-eigen` can be used to solve the problem as follows

Initialize the variables. Please notice that the `constraintMatrix` size is `0 x 2` (i.e. number of constraints x number of unknowns) 

```cpp
Eigen::SparseMatrix<double> hessian(2,2);
Eigen::SparseMatrix<double> constraintMatrix(0,2);
Eigen::Vector2d gradient;
Eigen::VectorXd bound(0);

gradient.setZero();
hessian.insert(0,0) = 1;
hessian.insert(1,1) = 1;
```

Now  you can initialize the problem as usual
```cpp
OsqpEigen::Solver solver;
solver.data()->setNumberOfVariables(2);
solver.data()->setNumberOfConstraints(0);
if(!solver.data()->setHessianMatrix(hessian)) return 1;
if(!solver.data()->setGradient(gradient)) return 1;
if(!solver.data()->setLinearConstraintsMatrix(constraintMatrix)) return 1;
if(!solver.data()->setLowerBound(bound)) return 1;
if(!solver.data()->setUpperBound(bound)) return 1;
```

You can finally solve the problem 

```cpp
if(!solver.initSolver()) return 1;
if(!solver.solve()) return 1;
```

Here the entire example

```cpp
#include <iostream>

#include <Eigen/Sparse>
#include <Eigen/Dense>

#include <OsqpEigen/OsqpEigen.h>

int main()
{
    Eigen::SparseMatrix<double> hessian(2,2);
    Eigen::SparseMatrix<double> constraintMatrix(0,2);
    Eigen::Vector2d gradient;
    Eigen::VectorXd bound(0);

    gradient.setZero();
    hessian.insert(0,0) = 1;
    hessian.insert(1,1) = 1;

    OsqpEigen::Solver solver;
    solver.data()->setNumberOfVariables(2);
    solver.data()->setNumberOfConstraints(0);
    if(!solver.data()->setHessianMatrix(hessian)) return 1;
    if(!solver.data()->setGradient(gradient)) return 1;
    if(!solver.data()->setLinearConstraintsMatrix(constraintMatrix)) return 1;
    if(!solver.data()->setLowerBound(bound)) return 1;
    if(!solver.data()->setUpperBound(bound)) return 1;

    if(!solver.initSolver()) return 1;
    if(!solver.solve()) return 1;

    std::cout << "Solution = " << solver.getSolution().transpose() << std::endl;

    return 0;
}
```

This is the `CMakeLists.txt` that you can use to run the example
```cmake
project(osqp-eigen-test)

cmake_minimum_required(VERSION 3.0)

find_package(OsqpEigen REQUIRED)
find_package(osqp REQUIRED)
find_package(Eigen3 REQUIRED)

add_executable(osqp-eigen-test main.cpp)
target_link_libraries(osqp-eigen-test OsqpEigen::OsqpEigen osqp::osqp Eigen3::Eigen)
```

The fact that the user should set the constraint matrix and the bounds even if the problem is unconstrained is counterintuitive.

cc @S-Dafarra @traversaro @lrapetti

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This Fixes #84

### CODE REVIEW

**Comment by S-Dafarra** [comment]
It think it might be worse bumping the version, even just the minor.

**Comment by GiulioRomualdi** [comment]
We should understand why the test fails in Windows. Unfortunately I don't have a PC with visual studio installed

**Comment by GiulioRomualdi** [comment]
The problem was the `alpha`. 191439a should fix the test. 

I also bump the version to` 0.6.2`. Once The PR got merged a will create a new release so we can use the code in `bipedal-locomotion-framework`

cc @traversaro

**Comment by GiulioRomualdi** [comment]
I actually noticed that osqp-eigen 0.6.2 has been already released but the cmake file contained 0.6.1. My bad. This new version will be 0.6.3

**Comment by GiulioRomualdi** [comment]
@S-Dafarra and @traversaro let me know if you’re fine with the pr

**Review by traversaro — APPROVED** [review]

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
