### PR TITLE
Resolved Compilation error when using float

### PR DESCRIPTION
**Pull request by voldien**
Resolves compilation error when c_float is set to float.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Hi @voldien thank you for your contribution! We really appreciate it. I will try review the PR before the end of this week

**Comment by wxmerkt** [comment]
This change will break compilation with double. Templating might be a solution, however I believe that casting in user-applications is the correct approach. @voldien, can you try `....getSolution().cast<c_float>()` in your application without changing the osqp-eigen? Would this resolve your issues?

**Comment by voldien** [comment]
The compilation error is caused by changing the c_float inside osqp to float instead of double. Since i trying to increase performance for my application. 

So the compilation error is not on my not on my side, since then I would just cast it as you mention. rather the compilation error is inside both OsqpEigen::Solver::getDualSolution() and OsqpEigen::Solver::getSolution(). Since it tries to pass a float pointer to VectorXd.

I thought the reason for it being a double for these two methods was just a miss, since the rest of variables and methods in the class are using the c_float.

**Comment by wxmerkt** [comment]
Right, I missed this - you're correct

**Comment by GiulioRomualdi** [comment]
Thank you very much @voldien! Merging!

**Pull request merged**
